[package]

name = "world-file"
description = "Rust read/write support for world files"
version = "0.0.1"
authors = ["Corey Farwell <coreyf@rwell.org>"]
license = "Apache-2.0"
repository = "https://github.com/georust/rust-world-file"
